-- MySQL Script generated by MySQL Workbench
-- 10/05/15 10:56:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `data_cadastro` VARCHAR(100) NOT NULL,
  `data_ult_alter` VARCHAR(100) NULL,
  `senha` TEXT NOT NULL,
  `status` ENUM('ATIVO', 'INATIVO') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `mydb`.`grupos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`grupos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`grupos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cod` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(150) NULL,
  `data_criacao` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios_x_grupos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuarios_x_grupos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuarios_x_grupos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_usuario` INT NOT NULL,
  `fk_grupo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_idx` (`fk_usuario` ASC),
  INDEX `fk_grupo_idx` (`fk_grupo` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `mydb`.`acessos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`acessos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`acessos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `tipo` ENUM('VER_ED_REM','SIM_NAO') NOT NULL,
  `cod` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `mydb`.`grupos_x_acessos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`grupos_x_acessos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`grupos_x_acessos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_grupo` INT NOT NULL,
  `fk_acesso` INT NOT NULL,
  `valor` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_acesso_idx` (`fk_acesso` ASC),
  INDEX `fk_grupo_idx` (`fk_grupo` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
